name: ci

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - distr: debian
            distr_version: jessie
            tags: |
              moletti/molecule-debian:8
              moletti/molecule-debian:jessie
          - distr: debian
            distr_version: stretch
            tags: |
               moletti/molecule-debian:9
               moletti/molecule-debian:stretch
          - distr: debian
            distr_version: buster
            tags: |
               moletti/molecule-debian:10
               moletti/molecule-debian:buster

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.distr }}
        push: true
        build-args: "OS_RELEASE=${{ matrix.distr_version }}"
        tags: ${{ matrix.tags }}